FROM ghcr.io/puppeteer/puppeteer:23.10.3

ENV PUPPETEER_SKIP_DOWNLOAD=false

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

# Install Chrome explicitly
RUN npx puppeteer browsers install chrome

COPY . .

CMD ["node", "index.js"]
